
- hosts: 127.0.0.1
  connection: local
  tasks:
   - name: generate vms locally
     shell: "{{  playbook_dir }}/generate-vms-locally.sh '{{ sourcevmx }}' '{{target_vm_dir }}' '{{ targetvmx }}' '{{ targetlinked1vmx }}' '{{ targetlinked2vmx }}' check"
     register: generate

   - debug: msg="{{ generate.stdout }}"

   - debug: msg="{{ generate.stderr }}"

   - name: Modify link1 vmx
     lineinfile:
       backup: yes
       dest: "{{ linked1vmx }}"
       regexp: "{{ item.regexp }}"
       line: "{{ item.line }}"
     with_items:
       - { regexp: 'ethernet0.addressType', line: 'ethernet0.addressType = "static"' }
       - { regexp: 'ethernet0.address', line: 'ethernet0.address = "{{ linked1_ethernet0_address }}"' }
       - { regexp: 'displayName', line: 'displayName = "GuerillaVM{{ target_vm_version_suffix }}-L1"' }
       - { regexp: 'sharedFolder0.present', line: 'sharedFolder0.present = "TRUE"' }
       - { regexp: 'sharedFolder0.enabled', line: 'sharedFolder0.enabled = "TRUE"' }
       - { regexp: 'sharedFolder0.readAccess', line: 'sharedFolder0.readAccess = "TRUE"' }
       - { regexp: 'sharedFolder0.writeAccess', line: 'sharedFolder0.writeAccess = "TRUE"' }
       - { regexp: 'sharedFolder0.hostPath', line: 'sharedFolder0.hostPath = "{{ host_sharing_guerilla_dir }}/vm1/DataDir"' }
       - { regexp: 'sharedFolder0.guestName', line: 'sharedFolder0.guestName = "hostDataDir"' }
       - { regexp: 'sharedFolder0.expiration', line: 'sharedFolder0.expiration = "never"' }
       - { regexp: 'sharedFolder.maxNum', line: 'sharedFolder.maxNum = "1"' }

   - name: Modify link2 vmx
     lineinfile:
       backup: yes
       dest: "{{ linked2vmx }}"
       regexp: "{{ item.regexp }}"
       line: "{{ item.line }}"
     with_items:
       - { regexp: 'ethernet0.addressType', line: 'ethernet0.addressType = "static"' }
       - { regexp: 'ethernet0.address', line: 'ethernet0.address = "{{ linked2_ethernet0_address }}"' }
       - { regexp: 'displayName', line: 'displayName = "GuerillaVM{{ target_vm_version_suffix }}-L2"' }
       - { regexp: 'sharedFolder0.present', line: 'sharedFolder0.present = "TRUE"' }
       - { regexp: 'sharedFolder0.enabled', line: 'sharedFolder0.enabled = "TRUE"' }
       - { regexp: 'sharedFolder0.readAccess', line: 'sharedFolder0.readAccess = "TRUE"' }
       - { regexp: 'sharedFolder0.writeAccess', line: 'sharedFolder0.writeAccess = "TRUE"' }
       - { regexp: 'sharedFolder0.hostPath', line: 'sharedFolder0.hostPath = "{{ host_sharing_guerilla_dir }}/vm2/DataDir"' }
       - { regexp: 'sharedFolder0.guestName', line: 'sharedFolder0.guestName = "hostDataDir"' }
       - { regexp: 'sharedFolder0.expiration', line: 'sharedFolder0.expiration = "never"' }
       - { regexp: 'sharedFolder.maxNum', line: 'sharedFolder.maxNum = "1"' }